# demo_setup.yml

- hosts: localhost
  gather_facts: False

  tasks:

    - name: Provision an ubuntu instance
      ec2:
        key_name: "MyKeyPair"
        group: test
        instance_type: t2.micro
        image: ami-087855b6c8b59a9e4 
        wait: true
        exact_count: 1
        count_tag:
           Name: Demo
        instance_tags:
           Name: Demo
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      loop: "{{ ec2.instances }}"
